version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: app_user_role
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/port
    ports:
      - "3000:3000"
    environment:
      PGHOST: 127.0.0.1
      DATABASE_PORT: 5432
      DATABASE_USER: app_user_role
      DATABASE_PASSWORD: password
    depends_on:
      - db
      