version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DATABASE: app_user_role
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - PGHOST=127.0.0.1
      - DATABASE_PORT=5432
      - DATABASE_USER=app_user_role
      - DATABASE_PASSWORD=password
    ports:
      - "3000:3000"
    depends_on:
      - db