version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          - BUNDLER_VERSION: 2.2.21  
          - POSTGRES_USER: app_user_role
      - image: circleci/postgres
        environment:
          - POSTGRES_USER: app_user_role
          - POSTGRES_PASSWORD: password
    working_directory: ~/port
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variable
          command: |
            echo "export COMPOSE_FILE=docker-compose.ci.yml" >> $BASH_ENV
      - run:
          name: Start containers and verify it is working
          command: |
            docker-compose down --rmi all
            docker-compose build
            docker-compose up -d
      - run:
          name: Setup database
          command: |
            docker-compose run web bundle install
            docker-compose run --rm web rails db:create
            docker-compose run web rails db:migrate
      - run:
          name: Run rspec
          command: docker-compose exec web rspec
      - run:
          name: Run rubocop
          command: docker-compose exec web rubocop
      - run:
          name: docker-compose down
          command: docker-compose down
