version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.8-node-browsers
        environment:
          - BUNDLER_VERSION: 2.2.33
          - RAILS_ENV: test
          - POSTGRES_USER: app_user_role
      - image: circleci/postgres
        environment:
          - POSTGRES_USER: app_user_role
          - POSTGRES_PASSWORD: <%= ENV['POSTGRES_PASSWORD'] %>
          - POSTGRES_DB: port_test
          # - POSTGRES_ROOT_HOST: '%'
    environment:
      - PGHOST: 127.0.0.1
    working_directory: ~/port
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.2.33
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: DBの起動を待つ
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - run:
          name: Setup database
          command: |
            sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7.1.0 /usr/lib/x86_64-linux-gnu/libffi.so.6
            bundle exec rails db:create
            bundle exec rails db:migrate
            bundle exec rails webpacker:install
      - run:
          name: Run rspec
          command: bundle exec rspec
      - run:
          name: Run rubocop
          command: bundle exec rubocop
