version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          - BUNDLER_VERSION: 2.2.21
          - RAILS_ENV: test
          - POSTGRES_USER: app_user_role
          - PGHOST: 127.0.0.1
      - image: circleci/postgres
        environment:
          - POSTGRES_USER: app_user_role
          - POSTGRES_PASSWORD: password
          - POSTGRES_DB: port_test
    working_directory: ~/port
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.2.21
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: DBの起動を待つ
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - run:
          name: Setup database
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate
      - run:
          name: Run rspec
          command: bundle exec rspec
      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: docker-compose down
          command: docker-compose down
