version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          - BUNDLER_VERSION: 2.2.21
          - POSTGRES_USER: app_user_role
          - RAILS_ENV: test
          - PGHOST: 127.0.0.1
      - image: circleci/postgres
        environment:
          - POSTGRES_USER: app_user_role
          - POSTGRES_PASSWORD: password
          - POSTGRES_DB: port_test
    working_directory: ~/port
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Start containers and verify it is working
          command: |
            docker-compose down --rmi all
            docker-compose build
            docker-compose up -d
      - run:
          name: Setup database
          command: |
            docker-compose run web bundle install
            docker-compose run --rm web rails db:create RAILS_ENV=test
            docker-compose run web rails db:migrate
      - run:
          name: Run rspec
          command: docker-compose run web bundle exec rspec
      - run:
          name: Run rubocop
          command: docker-compose run web bundle exec rubocop
      - run:
          name: docker-compose down
          command: docker-compose down
